### ISSUE TITLE
issues storing horse

### ISSUE THREAD

**Issue by Darkool** [izbay/stablemaster#8]
Hello great plugin, i have an issue storing horse on spigot 1.8 
http://pastebin.com/cdm6DBEu

Issues
*It spawn ponies
*I can't store my horse (error)
*if I spawn horse, other player can mount this and stole before i touch this(maybe add owner)
*make invulnerable horse            

regards

**Comment by DrkMatr1984** [comment]
I think most of these errors were fixed in the latest update. I'm going to close this and if it becomes a problem again people can open new tickets.
